services:
  c1:
    image: nginx:latest
    ports:
      - 91:80
      - 92:8000
      - 93:8080
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=testeff
      - tsdproxy.ephemeral=true
      - tsdproxy.funnel=true
      - tsdproxy.container_port=80
      - tsdproxy.dash.visible=true
    networks:
      - c1

  c2:
    image: nginx:1.27
    ports:
      - 82:80
    labels:
      - tsdproxy.enable=true
    networks:
      - c2

  c3:
    image: nginxinc/nginx-unprivileged:latest
    ports:
      - 83:8080
    labels:
      - tsdproxy.enable=true

  s1:
    image: nginx
    ports:
      - 101:80
      - 102:8000
      - 103:8080
    deploy:
      labels:
        - tsdproxy.enable=true
        - tsdproxy.name=testeff
        - tsdproxy.ephemeral=true
        - tsdproxy.funnel=true
        - tsdproxy.container_port=80
        - tsdproxy.dash.visible=true
    networks:
      - c1

  s2:
    image: nginx
    ports:
      - 112:80
    deploy:
      labels:
        - tsdproxy.enable=true
    networks:
      - c2

  s3:
    image: nginx
    network_mode: host
    ports:
      - 113:80
    deploy:
      labels:
        - tsdproxy.enable=true

volumes:
  tsdata:
  tmp:

networks:
  c1:
  c2:
